### ISSUE TITLE
Density type plot outputs data transposed

### ISSUE THREAD

**Issue by jip** [jsoftware/graphics_plot#2]
```
      JVERSION
Engine: j9.6.0-beta1/j64/linux
Build: commercial/2023-12-27T20:27:14/clang-11-0-0/SLEEF=1
Library: 9.6.1
Qt IDE: 2.5.2/5.12.8(5.15.8)
OS Ver: openSUSE Leap 15.5 5.14.21-150500.55.44-default
Platform: Linux 64
Installer: j9.6 install
InstallPath: /home/user/j9.6.0-beta1_j64avx2
Contact: www.jsoftware.com
   load 'plot'
   'density' plot i. 5 10
```
displays:
![plot_density_bug](https://github.com/jsoftware/graphics_plot/assets/313305/d48bc57f-4ed1-4147-809b-4ec8a9907f0e)

It seems the array is displayed transposed here: its rows are layed down by columns in the graph.

**Comment by cdburke** [comment]
I think this is intentional, though the design may not be right.
Internally, density is treated like a 3d plot, so the first axis would be
shown as the horizontal axis. It is probably too late to change this, so
you would have to transpose the argument.

**Comment by jip** [comment]
Ok, no problem.
